site_name: Oronymzy's tips
nav:
  - Home: 'README.md'
  - Content creation:
    - 'insCOSs.md'
    - 'instGit.md'
    - 'insMkDc.md'
    - 'instpip.md'
    - 'insPyth.md'
    - 'islGHsr.md'
    - 'undGitc.md'
    - 'usngGit.md'
    - 'usgMkDc.md'
  - Digital preservation:
    - 'cmscFMA.md'
    - 'gdskscr.md'
    - 'glslnkw.md'
  - Dweb:
    - 'ebsdatp.md'
  - Privacy:
    - 'chghstn.md'
    - 'dtnhstn.md'
    - 'dtnIPad.md'
    - 'insFDrd.md'
  - Web syndication:
    - 'gRSSiTn.md'
markdown_extensions:
  - admonition
  - footnotes
  - markdown.extensions.attr_list
  - pymdownx.details
  - pymdownx.keys
  - pymdownx.tasklist:
      custom_checkbox: true
theme:
  name: 'material'
