site_name: tips
nav:
  - Home: 'README.md'
  - Glossary: 'glossry.md'
  - Coding:
    - including code comments: 'incdcmt.md'
    - installing Git: 'instGit.md'
    - installing Go: 'instlGo.md'
    - installing Python: 'insPyth.md'
    - rewriting Git history: 'rGithst.md'
    - undoing a Git commit: 'undGitc.md'
    - using Git: 'usngGit.md'
  - Content creation:
    - installing Krita: 'insKrta.md'
    - installing software from the latest GitHub software release: 'islGHsr.md'
  - Data conversion:
    - replacing non-breaking spaces in a text file: 'rplnbst.md'
    - using FFmpeg: 'usFFmpg.md'
    - using ImageMagick: 'usIMgck.md'
    - using pandoc: 'uspndoc.md'
    - using SoX: 'usngSoX.md'
  - Data management:
    - installing DB Browser for SQLite: 'inDBSQL.md'
    - installing jq: 'instljq.md'
    - installing yq: 'instlyq.md'
    - listing all files containing specific text: 'lsfctxt.md'
    - using yq: 'usingyq.md'
  - Digital preservation:
    - collecting music from the Free Music Archive: 'cmscFMA.md'
    - embedding Exif metadata into an image: 'emExfmi.md'
    - getting a desktop screenshot: 'gdskscr.md'
    - getting a web page screenshot: 'gwebscr.md'
    - getting a list of URLs from a website: 'glsURLs.md'
    - installing Lloyd Brookes's renamer: 'inLBrnm.md'
    - installing pup: 'instpup.md'
    - installing uGet: 'instuGt.md'
    - installing youtube-dl: 'insytdl.md'
    - making a file executable: 'mkfexec.md'
    - opening multiple URLs: 'opmURLs.md'
    - using pup: 'usngpup.md'
    - using Lloyd Brookes's renamer: 'usLBrnm.md'
    - using youtube-dl: 'usgytdl.md'
  - Hardware:
    - getting hardware information: 'ghdinfo.md'
  - Leisure:
    - finding freely-licensed content: 'findflc.md'
    - installing beets: 'insbeet.md'
    - installing Google Chrome: 'insGCrm.md'
    - query API for ccMixter: 'qAPIccx.md'
    - using beets: 'usgbeet.md'
    - using Google: 'usGoogl.md'
  - Package management:
    - installing Bower: 'inBower.md'
    - installing Node.js and npm with nvm: 'inNjspv.md'
    - installing pip: 'instpip.md'
    - installing Ruby Version Manager: 'insRVMr.md'
  - Presentation:
    - indicating page breaks in Markdown: 'ipbkMkd.md'
    - Markdown reference: 'Mdwnref.md'
    - using PyMdown: 'usPyMdn.md'
    - using Python-Markdown: 'usPythM.md'
    - using reveal.js: 'usrevjs.md'
  - Privacy:
    - changing an environment variable: 'chgevtb.md'
    - changing the hostname: 'chghstn.md'
    - determining the hostname: 'dtnhstn.md'
    - determining the IP address: 'dtnIPad.md'
    - establishing a USB kill switch: 'esUSBks.md'
    - installing F-Droid: 'insFDrd.md'
    - installing VeraCrypt: 'insVCpt.md'
    - installing VirtualBox: 'instVBx.md'
    - using GNU GRUB: 'usgGRUB.md'
  - Sharing:
    - enabling browser support for the dat protocol: 'ebsdatp.md'
    - installing Beaker Browser: 'insBkrB.md'
    - installing qBittorrent: 'insqBtr.md'
    - migrating qBittorrent settings: 'mgqBtst.md'
    - migrating Transmission settings: 'mgTrnsm.md'
  - System software:
    - installing a CentOS system: 'insCOSs.md'
    - installing a Linux system: 'insLnxS.md'
  - Web development:
    - installing Atom text editor: 'insAtom.md'
    - installing Browsersync: 'inBsync.md'
    - installing Hugo: 'insHugo.md'
    - installing Jekyll: 'insJkyl.md'
    - installing MkDocs: 'insMkDc.md'
    - using Atom text editor: 'usgAtom.md'
    - using Browsersync: 'usBsync.md'
    - using CSS: 'usngCSS.md'
    - using HTML: 'usgHTML.md'
    - using MkDocs: 'usgMkDc.md'
    - using rsync: 'usrsync.md'
  - Web syndication:
    - getting an RSS feed for an iTunes podcast: 'gRSSiTn.md'
markdown_extensions:
  - admonition
  - attr_list
  - codehilite:
      guess_lang: false
  - def_list
  - footnotes
  - meta
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.extrarawhtml
  - pymdownx.keys
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
theme:
  name: 'material'
extra_css:
  - 'extra.css'
extra:
  social:
    - type: 'github'
      link: 'https://github.com/oronymzy'
repo_name: 'oronymzy/tips'
repo_url: 'https://github.com/oronymzy/tips'
edit_uri: ''
copyright: 'Freely licensed. See <a href="#licensing">§licensing</a> for more information.'
