site_name: Oronymzy's tips
nav:
  - Home: 'README.md'
  - Content creation:
    - installing a CentOS system: 'insCOSs.md'
    - installing a Linux system: 'insLnxS.md'
    - installing DB Browser for SQLite: 'inDBSQL.md'
    - installing Git: 'instGit.md'
    - installing Go: 'instlGo.md'
    - installing Krita: 'insKrta.md'
    - installing MkDocs: 'insMkDc.md'
    - installing pip: 'instpip.md'
    - installing Python: 'insPyth.md'
    - installing software from the latest GitHub software release: 'islGHsr.md'
    - rewriting Git history: 'rGithst.md'
    - undoing a Git commit: 'undGitc.md'
    - using Git: 'usngGit.md'
    - using MkDocs: 'usgMkDc.md'
  - Digital preservation:
    - collecting music from the Free Music Archive: 'cmscFMA.md'
    - getting a desktop screenshot: 'gdskscr.md'
    - getting a list of URLs from a website: 'glslnkw.md'
    - installing uGet: 'instuGt.md'
    - installing youtube-dl: 'insytdl.md'
  - Entertainment:
    - finding permissively-licensed content: 'findplc.md'
    - installing beets: 'insbeet.md'
    - installing Google Chrome: 'insGCrm.md'
  - Privacy:
    - changing an environment variable: 'chgevtb.md'
    - changing the hostname: 'chghstn.md'
    - determining the hostname: 'dtnhstn.md'
    - determining the IP address: 'dtnIPad.md'
    - installing F-Droid: 'insFDrd.md'
    - installing VirtualBox: 'instVBx.md'
    - using GNU GRUB: 'usgGRUB.md'
  - Sharing:
    - enabling browser support for the dat protocol: 'ebsdatp.md'
    - installing qBittorrent: 'insqBtr.md'
  - Web syndication:
    - getting an RSS feed for an iTunes podcast: 'gRSSiTn.md'
markdown_extensions:
  - admonition
  - footnotes
  - markdown.extensions.attr_list
  - pymdownx.details
  - pymdownx.keys
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
theme:
  name: 'material'
extra:
  social:
    - type: 'github'
      link: 'https://github.com/oronymzy'
