site_name: Oronymzy's tips
nav:
  - Home: 'README.md'
  - License: 'LICENSE.md'
  - Content creation:
    - 'instGit.md'
    - 'undGitc.md'
    - 'usngGit.md'
  - Digital preservation:
    - 'cmscFMA.md'
    - 'gdskscr.md'
    - 'glslnkw.md'
  - Dweb:
    - 'ebsdatp.md'
  - Privacy:
    - 'insFDrd.md'
markdown_extensions:
  - admonition
  - footnotes
  - pymdownx.details
  - pymdownx.keys
theme:
  name: 'material'
